name: CI
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            build:
                - java: 17
                  profile: codequality
                - java: 11
                  profile: java11
                - java: 8
                  profile: java8
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up JDK ${{ matrix.build.java }}
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4
        with:
          java-version: ${{ matrix.build.java }}
          distribution: 'temurin'
          cache: maven

      - name: Cache local Maven repository
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}${{ matrix.build.java }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}${{ matrix.build.java }}-maven-

      - name: Maven Verify
        run: mvn --batch-mode --activate-profiles e2e,${{ matrix.build.profile }} clean verify
